apiVersion: serving.knative.dev/v1
kind: Service
metadata: 
  annotations: 
    run.googleapis.com/launch-stage: BETA
  name: sidecar-test
spec: 
  template: 
    metadata: 
      annotations: 
        run.googleapis.com/execution-environment: ${GEN}
        run.googleapis.com/container-dependencies: '{"mainapp":["sidecar"]}'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'false'
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cloudsql-instances: ${GOOGLE_CLOUD_PROJECT}:asia-northeast1:test-instance
        run.googleapis.com/network-interfaces: '[{"network":"my-network","subnetwork":"my-network"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
    spec: 
      containerConcurrency: 1000
      containers: 
      - image: asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/my-app/mainapp
        startupProbe:
          httpGet:
            path: /ping
            # port: 8080
            httpHeaders:
              - name: X-MyGCP-Secret
                value: gcp
        name: mainapp
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        ports: 
        - containerPort: 8080
        volumeMounts: 
        - mountPath: /var/share
          name: share
        # startupProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 5
        #   timeoutSeconds: 1
        #   failureThreshold: 10
        #   periodSeconds: 2
      - image: asia-northeast1-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/my-app/sidecar
        name: sidecar
        resources: 
          limits: 
            cpu: "1"
            memory: 256Mi
        env:
          - name: GEN
            value: ${GEN}
          - name: DEBUG
            value: "1"
          - name: DEPLOY_START
            value: "${DEPLOY_START}"
        volumeMounts: 
        - mountPath: /var/share
          name: share
      volumes:
      - name: share
        emptyDir:
          medium: Memory
          sizeLimit: 8Mi
