apiVersion: serving.knative.dev/v1
kind: Service
metadata: 
  annotations: 
    run.googleapis.com/launch-stage: BETA
  name: ${SERVICE_NAME}
spec: 
  template: 
    metadata: 
      annotations: 
        run.googleapis.com/execution-environment: ${GEN}
        # run.googleapis.com/container-dependencies: '{"shellapp":["sidecar"]}'
        run.googleapis.com/cpu-throttling: 'true'
        run.googleapis.com/startup-cpu-boost: 'true'
        autoscaling.knative.dev/maxScale: '1'
        autoscaling.knative.dev/minScale: '0'
        run.googleapis.com/cloudsql-instances: ${GOOGLE_CLOUD_PROJECT}:${REGION}:test-instance
        run.googleapis.com/network-interfaces: '[{"network":"my-network","subnetwork":"my-network"}]'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/ingress: all
    spec: 
      containerConcurrency: 100
      timeoutSeconds: 3600
      containers: 
      - image: ${REGION}-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/my-app/shellapp
        name: shellapp
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
        ports: 
        - containerPort: 8080
          name: h2c
        volumeMounts: 
        - mountPath: /var/share
          name: share
        env:
          - name: DEPLOY_START
            value: "${DEPLOY_START}"
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          failureThreshold: 10
          periodSeconds: 2
      - image: ${REGION}-docker.pkg.dev/${GOOGLE_CLOUD_PROJECT}/my-app/sidecar
        name: sidecar
        # resources: 
        #   limits: 
        #     cpu: "4"
        #     memory: 2Gi
        env:
          - name: GEN
            value: ${GEN}
          - name: DEBUG
            value: "1"
          - name: DEPLOY_START
            value: "${DEPLOY_START}"
        volumeMounts: 
        - mountPath: /var/share
          name: share
      volumes:
      - name: share
        emptyDir:
          medium: Memory
          sizeLimit: 8Mi
